### ISSUE TITLE
Checklist for moving to OpenShift architecture

### ISSUE THREAD

**Issue by dharmit** [CentOS/container-pipeline-service#539]
Documents:

- [ ] Architecture diagram
- [ ] Architecture document

Items:

- [ ] Parsing the index entries
- [ ] Make parent-child relationships in Jenkins
- [ ] Polling the repos
    - [ ] Make a hook available to avoid polling
- [ ] Lint the Dockerfile
- [ ] Build the container image
- [ ] Scan the image
- [ ] Deliver the image to registry
- [ ] Notify the user via email
- [ ] Trigger repo tracking job and scan rpm data of the image
    - [ ] Ensure that it happens on image rebuild (in case new repo was enabled)
- [ ] Weekly scan in Jenkins
- [ ] Registry UI
- [ ] Registry tag cleanup/garbage collector
- [ ] Persistent volumes
    - [ ] Postgres database
        - [ ] Backup
    - [ ] Lint, build, scan, deliver logs
        - [ ] Backup
- [ ] Logging and monitoring data
    - [ ] Storage and backup
- [ ] Database schema redesign?
- [ ] Tests
    - [ ] Unit tests
    - [ ] Functional tests
- [ ] Ansible provisioning
    - [ ] openshift-ansible in production/pre-production
    - [ ] minishift/`oc cluster up` in development environment
    - [ ] Reliable way of upgrading openshift version from dev to pre-prod/prod

**Comment by bamachrn** [comment]
@dharmit do we want to keep this any more?
