### ISSUE TITLE
Sprint 147 Priorities

### ISSUE THREAD

**Issue by bamachrn** [CentOS/container-pipeline-service#542]
- [x] Fix weekly scan report to show proper report
- [x] Add link to target file in database #512
- [x] API for container pipeline shows build status data
- [ ] Refactoring CI invocation
- [ ] Documentation on how to use API
- [ ] Showing data on UI from API
- [ ] Get the architecture diagram and document
- [ ] Setup proper plugable scanner module to work on api based call
- [ ] Adding more docs to registry.centos.org 
- [x] Getting saas herder recieve data for git-url and commit id based on image id
- [x] Checking all the OSIO images if it required to build the dependency images
- [ ] Allow Users to opt for not receiving success mail and receive only failure emails #458 

Added later

- [x] misc-package-update scanner fails to remove container after scanning #544
- [x] RPM verify scanner's wrapper trying to access Summary info in case of failures #543
- [x] Enabling automatic gc runs in cron #514
- [ ] Registry UI title shows internal FQDN #508

**Comment by dharmit** [comment]
Below two issues need to be fixed in this sprint as well:

- [ ] misc-package-update scanner fails to remove container after scanning #544 
- [ ] RPM verify scanner's wrapper trying to access Summary info in case of failures #543

**Comment by navidshaikh** [comment]
This needs to be fixed
[ ] - Registry UI title shows internal FQDN https://github.com/CentOS/container-pipeline-service/issues/508

**Comment by bamachrn** [comment]
Sprint over
